### ISSUE TITLE
[Question] ensemble_retriever를 사용하는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by HyoTaek-Jang** [teddylee777/kakaotalk-gpt#3]
안녕하세요 테디님!

영상과, langchain 위키 등 양질의 자료로 정말 덕을 많이 보고 배우고 있습니다. 감사합니다.

다름이 아니라, 사이드 프로젝트 진행 중에 테디님은 어떤 식으로 retriever와 prompt를 작성하실까 궁금하여, 해당 프로젝트를 살펴보게 됐고, 질문이 생겨 이슈를 남기게 됐습니다.

1. 코드를 쭉 살펴보니, faiss와 chroma를 ensemble_retriever로 사용하시더라구요. 그 이유가 무엇인가요? 제가 생각했을 땐, faiss로는 임베딩된 백터 간 ann 검색을 통해 docs를 가져오고, chroma는 meta data 기반으로 SelfQueryRetriever를 사용하시려 했나 싶더라구요. 제가 생각한게 맞나요?
2. 1번이 맞다면, 그러면 metadata 기반으로 retriever를 하지 않고, 둘 다 faiss와 chroma 기본 알고리즘을 쓴다면 앙상블이 아닌 하나의 retriever만 사용해도 결과가 비슷할까요? 다른 아티클에서 faiss와 chroma를 같이 쓰는게 조합이 좋다고 봤는데 잘 이해가 안되더라구요. 둘다 ann, hnsw 알고리즘 기반으로 동작하는게 같은데 같이 쓴다 한 들 다른 결과가 나올까 싶어서요.
3. 마지막으로 다른 내용이긴 하나, prompt와 retriever 채팅 내용을 기반으로 말투를 따라하게 만드는게 가능할까요? 너무 모호한 질문이라 답변을 생략해주셔도 됩니다..ㅎㅎ 사실 찾아볼때 파인튜닝이 말투를 따라하는 캐릭터 ai를 만드는 데 적합하다고 들었지만, 혼자 상상할 땐 충분히 retriever된 데이터를 주고 비슷한 말투로 답 해줘. 요구하면 될 것 같았는데, 실제로 해보니 잘 안되더군요.. 혹시 비슷한 테스트를 하셨는지 경험이 궁금합니다.

질문이 참 길고, 모호한 질문도 있어서 죄송합니다. 답변에 어려움이 있다면 넘어가주셔도 좋습니다.

항상 좋은 자료 제공해주셔서 정말 감사하고, 오늘 하루도 행복하시길 바라겠습니다.

감사합니다.

**Comment by teddylee777** [comment]
@HyoTaek-Jang 님 안녕하세요!
아래에 답변 달아 놓겠습니다.

네, 1번 질문에 대한 내용 맞습니다.
Self Query 를 사용하기 위하여 Chroma 를 사용하였습니다.

조합이 좋다고 이야기 하는 것은 단순한 retriever 방식만 썼을때는 큰 시너지가 나지는 않을 것 같고요.
각각의 VectorStore 마다 지원하는 기능의 차이가 있는데요(이미지 임베딩, . 이 차이를 사용하여 보다 다양한 검색결과를 retrieve 해온 다음에 reranker 에 넣어서 최종 검색결과를 도출할 때 비로소 시너지가 날 수 있을 것 같습니다.
대용량 데이터를 적재하기 되면, 두 vectorstore 간 검색 성능 차이도 발생할 것 같고요~

말투 따라하는 것은 rag로도 흉내 낼 수는 있겠지만 finetuning 으로 접근하는 것이 더 효과적일 것 같습니다~

감사합니다.
